version: "1.0"
services:
  db:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: abcd@1234
      MYSQL_DATABASE: jobquest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

  backend:
    image: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/jobquest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abcd@1234
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    image: angular-frontend
    ports:
      - "4200:80"

volumes:
  db_data:
